# Environment

In [23]:
from sqlalchemy import create_engine, text
import pandas as pd
# import numpy as np
# import geopandas as gpd

# from functools import reduce

# import statsmodels.api as sm
# from sklearn.ensemble import RandomForestRegressor

# from econml.dml import CausalForestDML
# from sklearn.multioutput import MultiOutputRegressor


# import folium
# import branca.colormap as cm
# import webbrowser
# from tempfile import NamedTemporaryFile

# Data

In [24]:
DATABASE_URL = "postgresql+psycopg2://urban_user:urban_password@localhost:5433/urban_db"
engine = create_engine(DATABASE_URL, pool_pre_ping=True)

In [ ]:
uplifts_df = pd.read_sql("SELECT * FROM results.uplifts ", engine)
models_df = pd.read_sql("SELECT * FROM results.models ", engine)
hyppar_df = pd.read_sql("SELECT * FROM results.hyperparameters ", engine)
features_df = pd.read_sql("SELECT * FROM results.features ", engine)
shaps_df = pd.read_sql("SELECT * FROM results.shap_rf_reg_price ", engine)
#pred_reg_price_df = pd.read_sql("SELECT * FROM results.predicted_reg_price ", engine)
pred_reg_prices_df = pd.read_sql("SELECT * FROM results.predicted_reg_prices ", engine)

In [26]:
mined_df = pd.read_sql("SELECT * FROM mined.variables ", engine)

In [27]:
[c for c in mined_df['var_id'].unique().tolist() if 'socVrEduc' in c]

['socVrEduc_avrg_00000000']

# Results

In [35]:
pred_reg_prices_df

          model_id  block_id         costs
0    RF00000000001      1001  6.477029e+07
1    RF00000000001      1002  4.067135e+07
2    RF00000000001      1003  7.596574e+07
3    RF00000000001      1004  4.605636e+07
4    RF00000000001      1005  4.037401e+07
..             ...       ...           ...
260  RF00000000001      1278  3.872028e+07
261  RF00000000001      1279  1.027654e+08
262  RF00000000001      1280  4.056958e+07
263  RF00000000001      1281  4.194636e+07
264  RF00000000001      1282  4.674989e+07

[265 rows x 3 columns]

In [28]:
uplifts_df

      block_id       model_id treatment    uplift
0         1001  CF00000000001      d1nq  0.761337
1         1002  CF00000000001      d1nq  0.432922
2         1003  CF00000000001      d1nq  0.731237
3         1004  CF00000000001      d1nq  0.880556
4         1005  CF00000000001      d1nq  1.013777
...        ...            ...       ...       ...
1381      1280  CF00000000003       1nq  0.100849
1382      1281  CF00000000003       1nq  0.100849
1383      1282  CF00000000003       1nq  0.100849
1384      1283  CF00000000003       1nq  0.100849
1385      1284  CF00000000003       1nq  0.100849

[1386 rows x 4 columns]

In [29]:
models_df

,model_id,model_type,random_seed,target_id,pre_period,post_period,run_at
0,CF00000000001,Causal Forest with spatial spillovers of treat...,42,urVibBlPr_coun_00000000,2019,2025,2026-07-25 18:35:50.321337+00:00
1,CF00000000002,Causal Forest with spatial spillovers of treat...,42,urVibSCBx_coun_00000000,2019,2025,2026-07-25 18:38:56.704246+00:00
2,CF00000000003,Causal Forest with spatial spillovers of treat...,42,socVrEduc_avrg_00000000,2019,2025,2026-07-25 18:41:10.397244+00:00
3,RF00000000001,Random Forest Regeneration Cost,42,costs,2019,2025,2026-07-25 19:15:47.939836+00:00

In [30]:
hyppar_df

         model_id        hyper_parameter  value
0   CF00000000001           n_estimators    100
1   CF00000000001              max_depth      3
2   CF00000000001       min_samples_leaf     20
3   CF00000000001                 n_jobs      1
4   CF00000000001              criterion    mse
5   CF00000000001  min_impurity_decrease  0.001
6   CF00000000001           random_state    123
7   CF00000000002           n_estimators    100
8   CF00000000002              max_depth      3
9   CF00000000002       min_samples_leaf     20
10  CF00000000002                 n_jobs      1
11  CF00000000002              criterion    mse
12  CF00000000002  min_impurity_decrease  0.001
13  CF00000000002           random_state    123
14  CF00000000003           n_estimators    100
15  CF00000000003              max_depth      3
16  CF00000000003       min_samples_leaf     20
17  CF00000000003                 n_jobs      1
18  CF00000000003              criterion    mse
19  CF00000000003  min_impurity_decrease  0.001
20  CF00000000003           random_state    123
21  RF00000000001                  n_est    100
22  RF00000000001                 n_jobs      1
23  RF00000000001           random_state    123

In [31]:
features_df

         model_id  feature_no                   var_id  year
0   CF00000000001           0  bdEnvFRab_arrt_00000000  2019
1   CF00000000001           1  bdEnvFRxx_arrt_00000000  2019
2   CF00000000001           2  socVrPopt_coun_00000000  2021
3   CF00000000001           3  urVibSCBx_coun_00000000  2019
4   CF00000000002           0  bdEnvFRab_arrt_00000000  2019
5   CF00000000002           1  bdEnvFRxx_arrt_00000000  2019
6   CF00000000002           2  socVrPopt_coun_00000000  2021
7   CF00000000003           0  bdEnvFRab_arrt_00000000  2019
8   CF00000000003           1  bdEnvFRxx_arrt_00000000  2019
9   CF00000000003           2  socVrPopt_coun_00000000  2021
10  CF00000000003           3  urVibSCBx_coun_00000000  2019
11  RF00000000001           0                     area  2019
12  RF00000000001           1  bdEnvCaPr_arrt_00000000  2019
13  RF00000000001           2  bdEnvFRab_arrt_00000000  2019
14  RF00000000001           3  bdEnvFRxx_arrt_00000000  2019
15  RF00000000001           4  bdEnvFtxx_arrt_00000000  2019
16  RF00000000001           5  bdEnvKnrg_coun_00000000  2019
17  RF00000000001           6  bdEnvPlgr_coun_00000000  2019
18  RF00000000001           7  bdEnvSchl_coun_00000000  2019
19  RF00000000001           8  bdEnvScrb_arrt_00000000  2019
20  RF00000000001           9  urVibAOut_coun_00000000  2019
21  RF00000000001          10  urVibAlPn_coun_00000000  2019
22  RF00000000001          11  urVibBlPr_coun_00000000  2019
23  RF00000000001          12  urVibOfPn_coun_00000000  2019
24  RF00000000001          13  urVibPrUs_arrt_00000000  2019
25  RF00000000001          14  urVibSCBx_coun_00000000  2019
26  RF00000000001          15  socVrPopt_coun_00000000  2021