# Environment

In [ ]:
from sqlalchemy import create_engine, text
import pandas as pd
# import numpy as np
# import geopandas as gpd

# from functools import reduce

# import statsmodels.api as sm
# from sklearn.ensemble import RandomForestRegressor

# from econml.dml import CausalForestDML
# from sklearn.multioutput import MultiOutputRegressor


# import folium
# import branca.colormap as cm
# import webbrowser
# from tempfile import NamedTemporaryFile

# Data

In [16]:
DATABASE_URL = "postgresql+psycopg2://urban_user:urban_password@localhost:5433/urban_db"
engine = create_engine(DATABASE_URL, pool_pre_ping=True)

In [17]:
uplifts_df = pd.read_sql("SELECT * FROM results.uplifts ", engine)
models_df = pd.read_sql("SELECT * FROM results.models ", engine)
hyppar_df = pd.read_sql("SELECT * FROM results.hyperparameters ", engine)
features_df = pd.read_sql("SELECT * FROM results.features ", engine)

In [12]:
mined_df = pd.read_sql("SELECT * FROM mined.variables ", engine)

In [15]:
[c for c in mined_df['var_id'].unique().tolist() if 'socVrEduc' in c]

['socVrEduc_avrg_00000000']

# Results

In [18]:
uplifts_df

      block_id       model_id treatment    uplift
0         1001  CF00000000001      d1nq  0.761337
1         1002  CF00000000001      d1nq  0.432922
2         1003  CF00000000001      d1nq  0.731237
3         1004  CF00000000001      d1nq  0.880556
4         1005  CF00000000001      d1nq  1.013777
...        ...            ...       ...       ...
1127      1280  CF00000000002       1nq  0.778351
1128      1281  CF00000000002       1nq  0.733340
1129      1282  CF00000000002       1nq  0.600508
1130      1283  CF00000000002       1nq  0.580803
1131      1284  CF00000000002       1nq  0.651223

[1132 rows x 4 columns]

In [19]:
models_df

,model_id,model_type,random_seed,target_id,pre_period,post_period,run_at
0,CF00000000001,Causal Forest with spatial spillovers of treat...,42,urVibBlPr_coun_00000000,2019,2025,2026-07-22 16:56:36.709120+00:00
1,CF00000000002,Causal Forest with spatial spillovers of treat...,42,urVibSCBx_coun_00000000,2019,2025,2026-07-23 07:08:34.703972+00:00

In [20]:
hyppar_df

         model_id        hyper_parameter  value
0   CF00000000001           n_estimators    100
1   CF00000000001              max_depth      3
2   CF00000000001       min_samples_leaf     20
3   CF00000000001                 n_jobs      1
4   CF00000000001              criterion    mse
5   CF00000000001  min_impurity_decrease  0.001
6   CF00000000001           random_state    123
7   CF00000000002           n_estimators    100
8   CF00000000002              max_depth      3
9   CF00000000002       min_samples_leaf     20
10  CF00000000002                 n_jobs      1
11  CF00000000002              criterion    mse
12  CF00000000002  min_impurity_decrease  0.001
13  CF00000000002           random_state    123

In [8]:
features_df

        model_id  feature_no                   var_id
0  CF00000000001           0  bdEnvFRab_arrt_00000000
1  CF00000000001           1  bdEnvFRxx_arrt_00000000
2  CF00000000001           2  socVrPopt_coun_00000000
3  CF00000000001           3  urVibSCBx_coun_00000000
4  CF00000000002           0  bdEnvFRab_arrt_00000000
5  CF00000000002           1  bdEnvFRxx_arrt_00000000
6  CF00000000002           2  socVrPopt_coun_00000000