# Environment

In [22]:
from sqlalchemy import create_engine, text
import pandas as pd
import numpy as np
import geopandas as gpd

from functools import reduce

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import shap


import folium
import branca.colormap as cm
import webbrowser
from tempfile import NamedTemporaryFile

import matplotlib.pyplot as plt

In [2]:
DATABASE_URL = "postgresql+psycopg2://urban_user:urban_password@localhost:5433/urban_db"
engine = create_engine(DATABASE_URL, pool_pre_ping=True)

## Functions

In [3]:
def calculate_effect_signifficance(df_with_uplifts_and_base):
    df_arg = df_with_uplifts_and_base.copy()    
    output_dict = {}
    for treated_col in ['treated_d1nq','treated_1nq']:

        series = df_arg[df_arg[treated_col] == 1][f'{treated_col}_uplift']

        att = series.mean()

        se = series.std(ddof=1) / np.sqrt(len(series))

        ci_low = att - 1.96 * se
        ci_high = att + 1.96 * se
        output_dict[treated_col] = [ci_low, att, ci_high]
    return output_dict



def show_map(
    gdf,
    value_col,
    geometry_col="geometry",
    cmap="blue",
    tiles="CartoDB positron",
    opacity=0.8,
):
    """
    Wyświetla interaktywną mapę GeoDataFrame w przeglądarce.

    Parameters
    ----------
    gdf : GeoDataFrame
        Dane przestrzenne.
    value_col : str
        Kolumna używana do kolorowania.
    geometry_col : str
        Nazwa kolumny geometrii.
    cmap : str
        "blue", "red", "yellow", "grey",
        "green", "purple", "brown"
    tiles : str
        Podkład mapy Folium.
    opacity : float
        Przezroczystość poligonów.
    """

    # Kolory prezentacyjne
    colors = {
        "blue":   (2, 87, 163),
        "red":    (227, 26, 28),
        "yellow": (224, 184, 24),
        "grey":   (210, 214, 216),
        "green":  (27, 158, 119),
        "purple": (117, 107, 177),
        "brown":  (140, 81, 10),
    }

    if cmap not in colors:
        raise ValueError(f"Nieznana paleta '{cmap}'.")

    gdf = gdf.copy()

    if geometry_col != gdf.geometry.name:
        gdf = gdf.set_geometry(geometry_col)

    # Folium wymaga WGS84
    if gdf.crs is not None and gdf.crs.to_epsg() != 4326:
        gdf = gdf.to_crs(4326)

    # Środek mapy
    center = gdf.unary_union.centroid
    m = folium.Map(
        location=[center.y, center.x],
        zoom_start=13,
        tiles=tiles
    )

    rgb = colors[cmap]
    color_hex = "#{:02x}{:02x}{:02x}".format(*rgb)

    colormap = cm.LinearColormap(
        colors=["white", color_hex],
        vmin=gdf[value_col].min(),
        vmax=gdf[value_col].max(),
    )

    def style_function(feature):
        value = feature["properties"][value_col]

        if value is None:
            fill = "#FFFFFF"
        else:
            fill = colormap(value)

        return {
            "fillColor": fill,
            "color": "black",
            "weight": 0.5,
            "fillOpacity": opacity,
        }

    folium.GeoJson(
        gdf,
        style_function=style_function,
        tooltip=folium.GeoJsonTooltip(
            fields=[value_col],
            aliases=[value_col]
        ),
    ).add_to(m)

    colormap.caption = value_col
    colormap.add_to(m)

    # Wyświetlenie bez ręcznego zapisywania pliku
    with NamedTemporaryFile("w", suffix=".html", delete=False, encoding="utf-8") as f:
        m.save(f.name)
        webbrowser.open("file://" + f.name)

    return m

# Loading data

In [ ]:
urban_blocks = gpd.read_postgis(
    'SELECT * FROM core.urban_blocks_geom',
    engine,
    geom_col='geometry'
)
mined_variables = pd.read_sql("SELECT * FROM mined.variables ", engine)

In [18]:
regeneration_actions = pd.read_sql(
    'SELECT * FROM regeneration.actions',
    engine
)
regeneration_real_costs_pre = regeneration_actions.groupby(
    'block_id').agg({'costs':'sum'}).reset_index().copy()
regeneration_real_costs = urban_blocks.merge(
    regeneration_real_costs_pre, on = 'block_id', how='left').fillna(0).copy()
regeneration_real_costs

,block_id,area,geometry,costs
0,1001,25389.106838,"MULTIPOLYGON (((6601689.04 5735833.841, 660164...",0.0
1,1002,10787.745512,"MULTIPOLYGON (((6601624.543 5735809.818, 66015...",0.0
2,1003,109588.773671,"MULTIPOLYGON (((6602616.047 5737225.06, 660258...",0.0
3,1004,45213.964449,"MULTIPOLYGON (((6602470.225 5737747.832, 66025...",0.0
4,1005,47167.262541,"MULTIPOLYGON (((6602336.337 5737726.126, 66022...",0.0
...,...,...,...,...
278,1280,21723.606460,"MULTIPOLYGON (((6601841.762 5738834.11, 660181...",0.0
279,1281,126047.346189,"MULTIPOLYGON (((6601720.574 5738672.881, 66018...",0.0
280,1282,78839.772846,"MULTIPOLYGON (((6601476.558 5738774.781, 66015...",0.0
281,1283,255954.892610,"MULTIPOLYGON (((6601420.201 5737947.108, 66011...",45914948.0
282,1284,142617.034915,"MULTIPOLYGON (((6601104.673 5738147.351, 66011...",93020754.0

In [42]:
main_feat_df_pre = mined_variables[
    mined_variables['year'] ==pd.Timestamp(
        '2019-01-01')].reset_index(drop=True).drop(columns = ['year'])#['var_id'].unique()
main_feat_df_pre2 = main_feat_df_pre[~main_feat_df_pre['var_id'].isin([
    'socVrAgex_avrg_00000000', 'socVrEduc_avrg_00000000', 
    'socVrUnmp_avrg_00000000', 'socVrWage_avrg_00000000', 'socVrAS00_avrg_00000000'])].copy()
main_feat_df = (
    main_feat_df_pre2
    .pivot_table(index='block_id', columns='var_id', values='value', aggfunc='first')
    .reset_index()
)
main_feat_df.columns.name = None
main_feat_df

,block_id,bdEnvCaPr_arrt_00000000,bdEnvFRab_arrt_00000000,bdEnvFRxx_arrt_00000000,bdEnvFtxx_arrt_00000000,bdEnvKnrg_coun_00000000,bdEnvPlgr_coun_00000000,bdEnvSchl_coun_00000000,bdEnvScrb_arrt_00000000,urVibAOut_coun_00000000,urVibAlPn_coun_00000000,urVibBlPr_coun_00000000,urVibOfPn_coun_00000000,urVibPrUs_arrt_00000000,urVibSCBx_coun_00000000
0,1001,0.151117,0.000000,0.926567,0.383313,0.0,0.0,0.0,0.000000,0.0,0.0,2.0,0.0,0.000000,0.0
1,1002,0.000000,0.000000,1.514260,0.511389,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
2,1003,0.000000,0.000000,0.807809,0.292859,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,1.0
3,1004,0.106491,0.000000,0.914380,0.207803,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.073981,1.0
4,1005,0.065248,0.000000,0.869632,0.182325,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,1280,0.000000,0.000000,0.962615,0.243341,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,0.0,0.000000,1.0
279,1281,0.012398,0.000000,0.561628,0.164812,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,3.0
280,1282,0.086553,0.034694,1.310976,0.291677,0.0,0.0,0.0,0.000000,1.0,0.0,0.0,0.0,0.000000,5.0
281,1283,0.048253,0.003551,0.823984,0.205129,0.0,0.0,0.0,0.002782,10.0,0.0,3.0,2.0,0.000000,21.0
282,1284,0.106409,0.031434,1.214312,0.244065,0.0,0.0,0.0,0.002965,2.0,0.0,0.0,0.0,0.000000,7.0

In [50]:
poptot_df = mined_variables[
    (mined_variables['year'] ==pd.Timestamp('2021-01-01'))
    &(mined_variables['var_id'] =='socVrPopt_coun_00000000')
                ].reset_index(drop=True).rename(columns = {
                    'value':'socVrPopt_coun_00000000'}).drop(columns = ['var_id', 'year']).copy()

model_df = regeneration_real_costs[['block_id', 'area']].merge(
    poptot_df, on = ['block_id'], how = 'left').merge(
    main_feat_df, on = ['block_id'], how = 'left').sort_values('block_id').copy()

# Input

In [48]:
hypp_dict = {
    'n_est' : 100,
    # 'max_depth' : 3,
    # 'min_samples_leaf' : 20,
    'n_jobs' : 1,
    # 'criterion' : 'mse',
    # 'min_impurity_decrease' : 0.001,
    'random_state' : 123
}
random_seed_arg = 42



unique_model_id = 'RF00000000001'

# Data preparation

In [71]:
regeneration_costs_train = regeneration_real_costs[
    regeneration_real_costs['costs'] != 0].sort_values('block_id').reset_index(drop=True)
regeneration_costs_predict = regeneration_real_costs[
    regeneration_real_costs['costs'] == 0].sort_values('block_id').reset_index(drop=True).drop(columns = ['costs'])
model_df_train = model_df[model_df['block_id'].isin(
    regeneration_costs_train['block_id'].unique().tolist())].reset_index(drop=True)
model_df_predict = model_df[model_df['block_id'].isin(
    regeneration_costs_predict['block_id'].unique().tolist())].reset_index(drop=True)

# Model train

In [63]:
X_train = model_df_train.set_index('block_id')
y_train = regeneration_costs_train['costs']


rf = RandomForestRegressor(
    n_estimators=hypp_dict['n_est'],
    random_state=hypp_dict['random_state'],
    n_jobs=hypp_dict['n_jobs']
)


rf.fit(X_train, y_train)

RandomForestRegressor(n_jobs=1, random_state=123)

In [87]:
explainer = shap.TreeExplainer(rf)

shap_values = explainer.shap_values(X_train)
shap_df_pre = pd.DataFrame(
    shap_values,
    columns=X_train.columns,
    index=X_train.index
)
shap_df_pre2 = shap_df_pre.reset_index()
shap_df_pre2['model_id'] = unique_model_id
id_cols = ["model_id", "block_id"]
value_cols = [c for c in shap_df_pre2.columns if c not in id_cols]

shap_long_df = shap_df_pre2.melt(
    id_vars=id_cols,
    value_vars=value_cols,
    var_name="var_id",
    value_name="value",
)

shap_long_df.sort_values(
    ['block_id', 'var_id']).reset_index(drop=True)

          model_id  block_id                   var_id         value
0    RF00000000001      1014                     area  2.455899e+06
1    RF00000000001      1014  bdEnvCaPr_arrt_00000000 -1.204022e+06
2    RF00000000001      1014  bdEnvFRab_arrt_00000000  3.252286e+06
3    RF00000000001      1014  bdEnvFRxx_arrt_00000000  2.113542e+05
4    RF00000000001      1014  bdEnvFtxx_arrt_00000000  3.064243e+05
..             ...       ...                      ...           ...
283  RF00000000001      1284  urVibAlPn_coun_00000000 -2.536056e+05
284  RF00000000001      1284  urVibBlPr_coun_00000000 -4.436049e+06
285  RF00000000001      1284  urVibOfPn_coun_00000000 -1.425159e+06
286  RF00000000001      1284  urVibPrUs_arrt_00000000 -5.450717e+05
287  RF00000000001      1284  urVibSCBx_coun_00000000 -2.723533e+05

[288 rows x 4 columns]

In [89]:
base_value = explainer.expected_value
base_value

array([59501571.93611111])

In [78]:
shap_values

array([[ 2.45589926e+06, -1.23440884e+07, -1.20402241e+06,
         3.25228562e+06,  2.11354211e+05,  3.06424273e+05,
        -5.21150292e+05, -1.39826850e+05,  5.60455430e+03,
        -3.41050321e+05, -1.23445509e+06, -3.89610338e+05,
        -5.77889845e+06, -1.95324241e+06, -1.16841462e+06,
        -4.11824766e+05],
       [ 8.65612664e+05, -1.07701001e+07, -1.22698232e+06,
         3.97817391e+06,  2.31602664e+05, -1.62926835e+06,
        -5.57246994e+05, -1.73143925e+05, -7.28731299e+04,
        -4.15634917e+05, -1.09488832e+06, -5.23318787e+05,
        -5.18497943e+06, -1.91983903e+06, -1.22941279e+06,
        -3.82158616e+05],
       [ 2.46913951e+06,  2.70103638e+07, -3.33094546e+05,
         8.65510501e+06,  9.14263758e+05,  1.86888522e+06,
         5.80483079e+06, -7.13397444e+04,  6.63581487e+04,
         4.91057287e+05, -6.92203961e+05, -4.02139353e+05,
         1.79901407e+07, -1.63310316e+06, -7.98026870e+04,
        -6.72737461e+05],
       [ 2.45295811e+06, -1.28514862e+07, -2.39914679e+06,
        -8.32215254e+06,  1.78713377e+05, -1.56196306e+05,
         3.40734672e+06, -1.47969361e+05, -6.96790247e+04,
        -6.87659034e+05, -1.39151779e+06, -1.03149435e+06,
        -6.12321025e+06, -2.24898979e+06, -1.68134268e+06,
        -6.03579911e+05],
       [-1.67594603e+06, -1.36122321e+07,  2.08285367e+06,
        -3.31993471e+06,  3.46527503e+05, -2.83668889e+05,
        -5.34475432e+05, -1.53812875e+05, -8.70905136e+04,
         9.07621152e+05, -5.09255953e+05,  4.15071510e+05,
        -5.81545358e+06, -2.88649942e+06, -1.58324433e+06,
         3.37216728e+05],
       [ 4.23556963e+06,  2.12708306e+07, -9.93640882e+05,
         6.21453958e+05, -1.96650055e+06,  1.31157400e+05,
        -9.02518990e+05,  1.07068208e+05,  1.81848768e+05,
         4.88372365e+05,  3.43315034e+06,  6.52937024e+04,
         1.24445152e+07,  3.50081328e+06, -1.73610985e+05,
        -3.76792606e+03],
       [ 5.37404242e+06,  1.70327484e+07,  1.39027744e+06,
         6.60653045e+06,  1.75921039e+06,  1.50261079e+06,
        -8.36961123e+05,  1.17147138e+05,  1.65695049e+05,
         4.95206241e+05,  5.96005851e+06,  3.03474638e+06,
         1.59740018e+07,  1.09768726e+07,  1.49856121e+05,
         1.06375096e+06],
       [ 4.80884546e+06, -9.57908095e+06,  5.72804145e+05,
         3.54281527e+06,  1.00844340e+06, -6.55499535e+05,
        -5.19436032e+05, -7.35800987e+04, -2.74978848e+05,
        -1.51124269e+05,  4.23070063e+06,  2.80707887e+04,
         1.21637344e+07, -2.10380573e+06,  1.28569020e+06,
         2.01569741e+06],
       [-5.32561071e+06, -1.48886801e+07,  1.19572941e+06,
        -7.96661643e+06, -1.69650130e+06,  9.65705016e+05,
        -6.56852218e+05, -1.51787073e+05, -9.95380934e+04,
        -4.93834488e+05, -8.49614915e+05, -9.47894356e+05,
        -6.33150956e+06, -2.28332737e+06, -1.85781995e+06,
        -1.07140384e+06],
       [-2.70292846e+06, -1.00759909e+07, -9.41751393e+05,
         2.93050000e+06,  1.08123513e+06,  7.35926622e+05,
        -5.39141373e+05, -1.85275049e+05, -7.22442846e+04,
        -1.81739981e+05, -7.69886877e+05, -5.73841055e+05,
        -5.75134252e+06, -2.29814474e+06,  3.79303547e+05,
        -6.84278949e+05],
       [-3.93368362e+06, -6.86321799e+06, -1.22056526e+06,
         2.59717315e+06, -7.59301519e+05,  3.06594537e+05,
        -5.27543877e+05, -1.74564424e+05, -8.16861416e+04,
         3.00404365e+05, -9.77847190e+05,  1.71053502e+03,
        -5.36994594e+06, -2.63656716e+06, -1.36852070e+06,
        -8.65096902e+05],
       [-3.69545092e+06, -1.16076374e+07, -5.02984709e+05,
        -4.54859259e+06, -4.02048796e+05,  2.89298564e+05,
        -5.41963546e+05, -8.75933381e+04, -6.05411473e+04,
        -3.41378069e+05, -1.03724162e+06, -2.03483702e+05,
        -6.15390069e+06, -2.19346270e+06,  4.81767788e+06,
        -8.41644354e+05],
       [ 6.34062603e+05, -9.98891611e+06, -5.60766643e+05,
        -5.74308155e+06,  1.26423094e+06,  1.21558067e+06,
        -4.21740449e+05, -4.89704650e+04, -9.22078626e+04,
        -4.57475619e+05, -7.01173260e+05, -3.74508923e+04,
        -6.05182098e+06, -2.06947490e+06,  4.75803451e+06,
         9.51969197e+05],
       [-1.78630663e+06,  1.40473165e+07,  3.64729836e+06,
         1.37545677e+06,  4.57143004e+05,  9.65810663e+05,
        -9.08184777e+05,  5.72968558e+05,  6.89175858e+01,
        -9.83262053e+04, -9.34436160e+05, -1.59789881e+05,
        -5.50640875e+06, -1.71718113e+06, -5.55340748e+05,
        -9.29132017e+05],
       [ 4.78586511e+06,  6.95892736e+06,  3.96407370e+06,
         3.44055033e+06,  2.74588629e+05,  7.50854370e+05,
        -7.94214289e+05,  4.15773755e+04,  8.04038056e+04,
        -2.91295279e+05, -1.05996096e+06, -3.96161321e+05,
        -4.90141509e+06, -1.62573376e+06, -7.12610529e+05,
         1.43317172e+04],
       [-6.26699739e+06,  1.42053309e+07, -7.33589339e+05,
         1.38197889e+06, -5.71237424e+05,  8.45047929e+05,
        -1.00205872e+06, -9.85495542e+04,  2.62762190e+03,
        -2.95329669e+05, -1.22130179e+06, -8.55582974e+05,
        -6.58715349e+06, -2.87493410e+06, -6.73918939e+05,
        -9.09737797e+05],
       [ 9.98755446e+05,  1.22568729e+07, -1.29121787e+06,
        -2.12230269e+06, -4.15145427e+05, -3.06040774e+06,
        -1.09750380e+06, -2.41476487e+02,  3.76581790e+04,
        -1.29176992e+05, -6.92275595e+05, -3.60208415e+05,
         9.51822008e+06, -2.88303645e+06,  3.62215386e+04,
        -9.48344714e+05],
       [ 5.26433010e+06,  1.64038893e+07,  1.81923257e+06,
         5.01803038e+06,  1.89721482e+06,  8.33979239e+05,
        -8.47483926e+05,  1.36622298e+05,  7.56106747e+04,
         2.28984391e+06, -9.29759647e+05, -2.53605575e+05,
        -4.43604925e+06, -1.42515944e+06, -5.45071657e+05,
        -2.72353277e+05]])

# Model predict

In [64]:
X_pred = model_df_predict.set_index('block_id')
y_pred = rf.predict(X_pred)

In [72]:
regeneration_costs_predict['costs'] = y_pred
regeneration_costs_predict_to_vis = regeneration_costs_predict.copy()
regeneration_costs_predict = regeneration_costs_predict.drop(columns = ['area', 'geometry'])
regeneration_costs_predict

     block_id        costs
0        1001  59699790.75
1        1002  41046572.68
2        1003  77719927.08
3        1004  43449707.62
4        1005  37801893.15
..        ...          ...
260      1278  41220465.24
261      1279  94297496.94
262      1280  41845004.63
263      1281  40649131.21
264      1282  45841566.89

[265 rows x 2 columns]

In [53]:
hyper_df_pre = pd.DataFrame(
    hypp_dict.items(),
    columns=["hyper_parameter", "value"]
)
hyper_df_pre['model_id'] = unique_model_id
hyper_df = hyper_df_pre[['model_id', "hyper_parameter", "value"]]
hyper_df

        model_id hyper_parameter  value
0  RF00000000001           n_est    100
1  RF00000000001          n_jobs      1
2  RF00000000001    random_state    123

In [55]:
df_model = pd.DataFrame({
    'model_id':[unique_model_id],
    'model_type':["Random forest"],
    'random_seed':[random_seed_arg],
    'target_id':['costs'],
              })
df_model

        model_id     model_type  random_seed target_id
0  RF00000000001  Random forest           42     costs

In [73]:
show_map(
    regeneration_costs_predict_to_vis,
    'costs',
    geometry_col="geometry",
    cmap="blue",
    tiles="CartoDB positron",
    opacity=0.8,
)

C:\Users\andre\AppData\Local\Temp\ipykernel_31684\1475656961.py:71: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  center = gdf.unary_union.centroid