# Environment

In [1]:
from sqlalchemy import create_engine, text
import pandas as pd
import numpy as np
import geopandas as gpd

from functools import reduce

from sklearn.ensemble import RandomForestRegressor
#from sklearn.metrics import mean_squared_error, r2_score
import shap


# import folium
# import branca.colormap as cm
# import webbrowser
# from tempfile import NamedTemporaryFile

# import matplotlib.pyplot as plt

In [2]:
DATABASE_URL = "postgresql+psycopg2://urban_user:urban_password@localhost:5433/urban_db"
engine = create_engine(DATABASE_URL, pool_pre_ping=True)

# Loading data

In [3]:
urban_blocks = gpd.read_postgis(
    'SELECT * FROM core.urban_blocks_geom',
    engine,
    geom_col='geometry'
)
mined_variables = pd.read_sql("SELECT * FROM mined.variables ", engine)

In [4]:
regeneration_actions = pd.read_sql(
    'SELECT * FROM regeneration.actions',
    engine
)
regeneration_real_costs_pre = regeneration_actions.groupby(
    'block_id').agg({'costs':'sum'}).reset_index().copy()
regeneration_real_costs = urban_blocks.merge(
    regeneration_real_costs_pre, on = 'block_id', how='left').fillna(0).copy()
regeneration_real_costs

,block_id,area,geometry,costs
0,1001,25389.106838,"MULTIPOLYGON (((6601689.04 5735833.841, 660164...",0.0
1,1002,10787.745512,"MULTIPOLYGON (((6601624.543 5735809.818, 66015...",0.0
2,1003,109588.773671,"MULTIPOLYGON (((6602616.047 5737225.06, 660258...",0.0
3,1004,45213.964449,"MULTIPOLYGON (((6602470.225 5737747.832, 66025...",0.0
4,1005,47167.262541,"MULTIPOLYGON (((6602336.337 5737726.126, 66022...",0.0
...,...,...,...,...
278,1280,21723.606460,"MULTIPOLYGON (((6601841.762 5738834.11, 660181...",0.0
279,1281,126047.346189,"MULTIPOLYGON (((6601720.574 5738672.881, 66018...",0.0
280,1282,78839.772846,"MULTIPOLYGON (((6601476.558 5738774.781, 66015...",0.0
281,1283,255954.892610,"MULTIPOLYGON (((6601420.201 5737947.108, 66011...",45914948.0
282,1284,142617.034915,"MULTIPOLYGON (((6601104.673 5738147.351, 66011...",93020754.0

# Input

In [5]:
hypp_dict = {
    'n_est' : 100,
    # 'max_depth' : 3,
    # 'min_samples_leaf' : 20,
    'n_jobs' : 1,
    # 'criterion' : 'mse',
    # 'min_impurity_decrease' : 0.001,
    'random_state' : 123
}
random_seed_arg = 42

pre_period = 2019

post_period = 2025

unique_model_id = 'RF00000000001'

# Data preparation

In [9]:
main_feat_df_pre = mined_variables[
    mined_variables['year'] ==pd.Timestamp(
        f'{pre_period}-01-01')].reset_index(drop=True).drop(columns = ['year'])
main_feat_df_pre2 = main_feat_df_pre[~main_feat_df_pre['var_id'].isin([
    'socVrAgex_avrg_00000000', 'socVrEduc_avrg_00000000', 
    'socVrUnmp_avrg_00000000', 'socVrWage_avrg_00000000', 'socVrAS00_avrg_00000000'])].copy()
main_feat_df = (
    main_feat_df_pre2
    .pivot_table(index='block_id', columns='var_id', values='value', aggfunc='first')
    .reset_index()
)
main_feat_df.columns.name = None

In [7]:
poptot_df = mined_variables[
    (mined_variables['year'] ==pd.Timestamp('2021-01-01'))
    &(mined_variables['var_id'] =='socVrPopt_coun_00000000')
                ].reset_index(drop=True).rename(columns = {
                    'value':'socVrPopt_coun_00000000'}).drop(columns = ['var_id', 'year']).copy()

model_df = regeneration_real_costs[['block_id', 'area']].merge(
    poptot_df, on = ['block_id'], how = 'left').merge(
    main_feat_df, on = ['block_id'], how = 'left').sort_values('block_id').copy()

In [8]:
regeneration_costs_train = regeneration_real_costs[
    regeneration_real_costs['costs'] != 0].sort_values('block_id').reset_index(drop=True)
regeneration_costs_predict = regeneration_real_costs[
    regeneration_real_costs['costs'] == 0].sort_values('block_id').reset_index(drop=True).drop(columns = ['costs'])
model_df_train = model_df[model_df['block_id'].isin(
    regeneration_costs_train['block_id'].unique().tolist())].reset_index(drop=True)
model_df_predict = model_df[model_df['block_id'].isin(
    regeneration_costs_predict['block_id'].unique().tolist())].reset_index(drop=True)

# Model train

In [10]:
X_train = model_df_train.set_index('block_id')
y_train = regeneration_costs_train['costs']


rf = RandomForestRegressor(
    n_estimators=hypp_dict['n_est'],
    random_state=hypp_dict['random_state'],
    n_jobs=hypp_dict['n_jobs']
)


rf.fit(X_train, y_train)

RandomForestRegressor(n_jobs=1, random_state=123)

In [27]:
explainer = shap.TreeExplainer(rf)

shap_values = explainer.shap_values(X_train)
shap_df_pre = pd.DataFrame(
    shap_values,
    columns=X_train.columns,
    index=X_train.index
)
shap_df_pre2 = shap_df_pre.reset_index()
shap_df_pre2['model_id'] = unique_model_id
id_cols = ["model_id", "block_id"]
value_cols = [c for c in shap_df_pre2.columns if c not in id_cols]

shap_long_df_pre3 = shap_df_pre2.melt(
    id_vars=id_cols,
    value_vars=value_cols,
    var_name="var_id",
    value_name="value",
)

base_value = explainer.expected_value

shap_base_value = shap_long_df_pre3[
    ['model_id', 'block_id']].drop_duplicates(['model_id', 'block_id'])
shap_base_value['var_id'] = 'base_value'
shap_base_value['value'] = base_value[0]
shap_long_df = pd.concat([shap_long_df_pre3,shap_base_value]).copy()
shap_long_df = shap_long_df.sort_values(
    ['block_id', 'var_id']).reset_index(drop=True)
shap_long_df

          model_id  block_id                   var_id         value
0    RF00000000001      1014                     area  2.455899e+06
1    RF00000000001      1014               base_value  5.950157e+07
2    RF00000000001      1014  bdEnvCaPr_arrt_00000000 -1.204022e+06
3    RF00000000001      1014  bdEnvFRab_arrt_00000000  3.252286e+06
4    RF00000000001      1014  bdEnvFRxx_arrt_00000000  2.113542e+05
..             ...       ...                      ...           ...
301  RF00000000001      1284  urVibAlPn_coun_00000000 -2.536056e+05
302  RF00000000001      1284  urVibBlPr_coun_00000000 -4.436049e+06
303  RF00000000001      1284  urVibOfPn_coun_00000000 -1.425159e+06
304  RF00000000001      1284  urVibPrUs_arrt_00000000 -5.450717e+05
305  RF00000000001      1284  urVibSCBx_coun_00000000 -2.723533e+05

[306 rows x 4 columns]

# Model predict

In [13]:
X_pred = model_df_predict.set_index('block_id')
y_pred = rf.predict(X_pred)

In [14]:
regeneration_costs_predict['costs'] = y_pred
regeneration_costs_predict_to_vis = regeneration_costs_predict.copy()
regeneration_costs_predict = regeneration_costs_predict.drop(columns = ['area', 'geometry'])
regeneration_costs_predict

     block_id        costs
0        1001  59699790.75
1        1002  41046572.68
2        1003  77719927.08
3        1004  43449707.62
4        1005  37801893.15
..        ...          ...
260      1278  41220465.24
261      1279  94297496.94
262      1280  41845004.63
263      1281  40649131.21
264      1282  45841566.89

[265 rows x 2 columns]

In [15]:
hyper_df_pre = pd.DataFrame(
    hypp_dict.items(),
    columns=["hyper_parameter", "value"]
)
hyper_df_pre['model_id'] = unique_model_id
hyper_df = hyper_df_pre[['model_id', "hyper_parameter", "value"]]
hyper_df

        model_id hyper_parameter  value
0  RF00000000001           n_est    100
1  RF00000000001          n_jobs      1
2  RF00000000001    random_state    123

In [16]:
df_model = pd.DataFrame({
    'model_id':[unique_model_id],
    'model_type':["Random forest"],
    'random_seed':[random_seed_arg],
    'target_id':['costs'],
    'pre_period':[pre_period],
    'post_period':[post_period],
              })
df_model

,model_id,model_type,random_seed,target_id,pre_period,post_period
0,RF00000000001,Random forest,42,costs,2019,2025

In [ ]:
#features_df = 
list_of_features = list(set(model_df.columns.tolist()).difference({'block_id'}))

features_df_pre = pd.DataFrame({'feature_no':[c for c in range(len(list_of_features))],
              'var_id': list_of_features})
features_df_pre['model_id'] = unique_model_id
features_df_pre['year'] = pre_period
features_df_pre.loc[features_df_pre['var_id'] == 'socVrPopt_coun_00000000', 'year'] = 2021
features_df = features_df_pre[['model_id', 'feature_no', 'var_id', 'year']]
features_df

In [ ]:
[c for c in range(len(list_of_features))]