In [1]:
from sqlalchemy import create_engine, text
import pandas as pd
import geopandas as gpd

import folium
import webbrowser
import os
from folium.plugins import MarkerCluster

In [2]:
DATABASE_URL = "postgresql+psycopg2://urban_user:urban_password@localhost:5433/urban_db"
engine = create_engine(DATABASE_URL, pool_pre_ping=True)

with engine.connect() as conn:
    result = conn.execute(text("SELECT version();"))
    print(result.fetchone()[0])

PostgreSQL 16.4 (Debian 16.4-1.pgdg110+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

In [ ]:
# with engine.connect() as conn:
#     # Co jest w full_adress w stagingu?
#     print("=== stg_addresses (pierwsze 5) ===")
#     rows = conn.execute(text(
#         "SELECT full_adress FROM audit.stg_addresses WHERE run_id=11 LIMIT 5"
#     )).fetchall()
#     for r in rows: print(repr(r[0]))

#     print("\n=== stg_penalties - place_of_penalty (pierwsze 5) ===")
#     rows = conn.execute(text(
#         "SELECT place_of_penalty FROM audit.stg_penalties WHERE run_id=11 LIMIT 5"
#     )).fetchall()
#     for r in rows: print(repr(r[0]))

In [ ]:
# with engine.begin() as conn:
#     conn.execute(text("DELETE FROM mined.penalties"))
#     conn.execute(text("DELETE FROM audit.stg_penalties WHERE run_id=11"))
#     conn.execute(text("DELETE FROM audit.processed_files WHERE dag_id='etl_penalties_addresses'"))
#     print("OK")

In [ ]:
# with engine.begin() as conn:
#     conn.execute(text("DELETE FROM audit.stg_penalties WHERE run_id IN (SELECT run_id FROM audit.etl_log WHERE dag_id='etl_penalties_addresses')"))
#     conn.execute(text("DELETE FROM mined.penalties"))
#     conn.execute(text("DELETE FROM audit.processed_files WHERE dag_id='etl_penalties_addresses'"))
#     print("OK")

In [3]:
# Sprawdź dostępne schematy
with engine.connect() as conn:
    schemas = conn.execute(text(
        "SELECT schema_name FROM information_schema.schemata ORDER BY schema_name;"
    ))
    print([r[0] for r in schemas])

['audit', 'core', 'information_schema', 'meta', 'mined', 'osm', 'pg_catalog', 'pg_temp_17', 'pg_temp_19', 'pg_temp_20', 'pg_toast', 'pg_toast_temp_17', 'pg_toast_temp_19', 'pg_toast_temp_20', 'public', 'regeneration', 'results']

In [4]:
# Sprawdź PostGIS
with engine.connect() as conn:
    result = conn.execute(text("SELECT PostGIS_Version();"))
    print("PostGIS:", result.fetchone()[0])

PostGIS: 3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

In [5]:
# Dane tabelaryczne
df = pd.read_sql("SELECT * FROM mined.variables ", engine)
df

                        var_id       year  block_id        value
0      bdEnvFtxx_arrt_00000000 2026-01-01      1001     0.393559
1      bdEnvFRxx_arrt_00000000 2026-01-01      1001     0.993033
2      bdEnvFtxx_arrt_00000000 2026-01-01      1002     0.476774
3      bdEnvFRxx_arrt_00000000 2026-01-01      1002     1.788587
4      bdEnvFtxx_arrt_00000000 2026-01-01      1003     0.245048
...                        ...        ...       ...          ...
21154  socVrPopt_coun_00000000 2021-01-01      1280   356.000000
21155  socVrPopt_coun_00000000 2021-01-01      1281   739.000000
21156  socVrPopt_coun_00000000 2021-01-01      1282   564.000000
21157  socVrPopt_coun_00000000 2021-01-01      1283  1148.000000
21158  socVrPopt_coun_00000000 2021-01-01      1284   972.000000

[21159 rows x 4 columns]

In [6]:
df['var_id'].unique()

array(['bdEnvFtxx_arrt_00000000', 'bdEnvFRxx_arrt_00000000',
       'urVibBlPr_coun_00000000', 'socVrAS00_avrg_00000000',
       'urVibAlPn_coun_00000000', 'urVibOfPn_coun_00000000',
       'urVibEnAl_coun_00000000', 'urVibEnBl_coun_00000000',
       'socVrAgex_avrg_00000000', 'socVrEduc_avrg_00000000',
       'socVrUnmp_avrg_00000000', 'socVrWage_avrg_00000000',
       'urVibPrUs_arrt_00000000', 'bdEnvFRab_arrt_00000000',
       'socVrPopt_coun_00000000'], dtype=object)

In [7]:
df[(df['var_id'] == 'socVrAS00_avrg_00000000')
   #&(df['value'] != 0)
   #&(df['block_id'] == 1001)
   #&(df['year'] == pd.Timestamp('2022-01-01'))
   ]#['block_id'].nunique()

                       var_id       year  block_id        value
3396  socVrAS00_avrg_00000000 2015-01-01      1117  2586.066892
3397  socVrAS00_avrg_00000000 2017-01-01      1018  3785.883210
3398  socVrAS00_avrg_00000000 2022-01-01      1071  4828.326180
3399  socVrAS00_avrg_00000000 2025-01-01      1124  6981.838817
3400  socVrAS00_avrg_00000000 2023-01-01      1139  1746.935326
...                       ...        ...       ...          ...
5689  socVrAS00_avrg_00000000 2024-01-01      1166  7295.426750
5690  socVrAS00_avrg_00000000 2019-01-01      1135  4895.463040
5691  socVrAS00_avrg_00000000 2016-01-01      1120  2829.537206
5692  socVrAS00_avrg_00000000 2025-01-01      1049  6198.098430
5693  socVrAS00_avrg_00000000 2022-01-01      1038  5939.727319

[2298 rows x 4 columns]

In [8]:
df[(df['var_id'] == 'socVrAS00_avrg_00000000')
   #&(df['value'] != 0)
   #&(df['block_id'] == 1001)
   #&(df['year'] == pd.Timestamp('2022-01-01'))
   ]['year'].value_counts()

year
2024-01-01    232
2025-01-01    227
2023-01-01    226
2022-01-01    225
2021-01-01    221
2019-01-01    220
2015-01-01    214
2016-01-01    213
2020-01-01    211
2017-01-01    188
2026-01-01    121
Name: count, dtype: int64

In [9]:
# Dane tabelaryczne
dfmeta = pd.read_sql("SELECT * FROM meta.var_description ", engine)
dfmeta

,var_id,unit,origin,description
0,urVibEnAl_coun_00000000,entrepreneurs,legacy,The number of registered enterpreneurs in a pa...
1,urVibEnBl_coun_00000000,buildings,legacy,The number of buildings with registered enterp...
2,socVrAgex_avrg_00000000,years,legacy,The average age of the inhabitants above 24 ag...
3,socVrEduc_avrg_00000000,category,legacy,The average education level of the inhabitants...
4,socVrUnmp_avrg_00000000,unemployment,legacy,The average unemployment level of the inhabita...
5,socVrWage_avrg_00000000,Average wage quantile,legacy,The average wage of the inhabitants in the par...
6,urVibPrUs_arrt_00000000,permits_to_use,legacy,The number of the issued permits to use in a p...
7,bdEnvFRab_arrt_00000000,area_ratio,legacy,The floor area ratio of abandoned buildings in...
8,socVrPopt_coun_00000000,count,Census 2021,Total population Census 2021
9,socVrAS00_avrg_00000000,pln,RCN,average price of the appartments in urban block
10,urVibBlPr_coun_00000000,count,Geoportal GUNB,The number of the issued building permits in a...
11,bdEnvFtxx_arrt_00000000,arrt,mapa_lodz/egib,Total building footprint area in an urban bloc...
12,bdEnvFRxx_arrt_00000000,arrt,mapa_lodz/egib,Total floor area (footprint × floors above gro...
13,urVibAlPn_coun_00000000,count,city_guard,The number of the penalties for alcohol consum...
14,urVibOfPn_coun_00000000,count,city_guard,The number of the penalties for offences in pu...

In [15]:
temp_check_df = df[(df['var_id'].isin(['urVibOfPn_coun_00000000']))
                   &(df['value'] != 0)
                   ]
temp_check_df['year'].value_counts()

year
2019-01-01    31
2022-01-01    30
2020-01-01    19
2023-01-01    16
2021-01-01    16
Name: count, dtype: int64

In [16]:
dfaudit = pd.read_sql("SELECT * FROM audit.etl_log ", engine)
dfaudit

,run_id,dag_id,source,started_at,finished_at,rows_extracted,rows_staged,rows_new,rows_loaded,status,error_msg
0,1,etl_build_perm,Geoportal GUNB WFS,2026-07-01 20:23:51.939193,2026-07-01 20:26:11.764387,16849,1351,1351,1351,success,None
1,2,etl_penalties_addresses,mapa_lodz/city_guard,2026-07-01 20:26:54.512853,2026-07-01 20:28:22.253798,14057,14057,1386,14057,success,None
2,3,etl_buildings,mapa_lodz/egib,2026-07-01 20:35:52.512865,2026-07-01 20:36:20.335889,26729,26729,26729,26729,success,None
3,4,etl_buildings,mapa_lodz/egib,2026-07-01 20:46:34.535420,2026-07-01 20:47:23.003369,26729,26729,26729,26729,success,None
4,5,etl_build_perm,Geoportal GUNB WFS,2026-07-04 19:48:46.717695,2026-07-04 19:49:13.806486,16851,1353,1353,1353,success,None
5,6,etl_penalties_addresses,mapa_lodz/city_guard,2026-07-04 19:49:37.792027,2026-07-04 19:49:52.249929,12671,12671,0,12671,success,None
6,7,etl_buildings,mapa_lodz/egib,2026-07-04 19:50:23.454640,2026-07-04 19:52:26.893833,26730,26730,26730,26730,success,None
7,8,etl_app_prices,RCN,2026-07-04 19:52:48.592158,2026-07-04 19:56:45.890777,1112,1112,1112,1112,success,None
8,9,etl_penalties_addresses,mapa_lodz/city_guard,2026-07-04 20:11:38.037248,2026-07-04 20:11:55.782153,12671,12671,0,12671,success,None

In [19]:
dfauditstg = pd.read_sql("SELECT * FROM audit.stg_build_perm ", engine)
dfauditstg

,id,run_id,build_perm_id,build_plot_no,issue_date,description,geometry,loaded_at,block_id
0,1,1,833406 UA.I MB,155/3,2020-11-20,NADBUD.O JEDNĄ KONDYGNACJĘ BUDYNKU WIELOR.,0101000020810800006C74A9350D2F59410BDE99757BE4...,2026-07-01 20:26:02.606259,1279
1,2,1,921676 UA.I,169/21,2020-12-30,"PRZEBUD.,NADBUD.I ZMIANA SPOS. UŻYTK.WRAZ Z PR...",010100002081080000D90B3DDFF42D5941FCFF6B45C0E4...,2026-07-01 20:26:02.606259,1224
2,3,1,389382 UA.I PW,158/54,2020-06-10,BUDOWA BUDYNKU BIUROWEGO OZN. J01 ORAZ ROZBIÓR...,01010000208108000010786483812E5941CE3B2F6C78E1...,2026-07-01 20:26:02.606259,1132
3,4,1,903478 UA.I,114/3,2020-12-21,"BUDOWA BUDYNKU WIELORODZINNEGO, ROZBIÓRKA BUDY...",01010000208108000091EE270A082E59416B90F99CB0E3...,2026-07-01 20:26:02.606259,1173
4,5,1,728464 UA.III,62,2020-10-13,BUDOWA ZESP. SYSTEMOWYCH GARAŻY JEDNOSTAN.,01010000208108000017110635D72F59414B5F18DAA1E1...,2026-07-01 20:26:02.606259,1051
...,...,...,...,...,...,...,...,...,...
2699,2700,5,171320 UA.I,54/14,2019-03-11,ZESPÓŁ BUDYNKÓW WIELOR. Z USŁUG. W PARTERZE PA...,0101000020810800006169E89D50305941FFBADFF5E1E2...,2026-07-04 19:49:06.727333,1031
2700,2701,5,658616 UA.I,1/43,2019-10-30,"PRZEBUDOWA, NADBUDOWA, ZMIANA SPOSOBU UŻYTKOWA...",0101000020810800007194C7EAD6305941B2629E3505E3...,2026-07-04 19:49:06.727333,1027
2701,2702,5,658616 UA.I,1/50,2019-10-30,"PRZEBUDOWA, NADBUDOWA, ZMIANA SPOSOBU UŻYTKOWA...",0101000020810800009E3BD4AFEB305941955E9151FEE2...,2026-07-04 19:49:06.727333,1027
2702,2703,5,604617 UA.III,18/4,2019-10-08,BUDOWA TRZECH BUDYNKÓW WIELORODZINNYCH Z GARAŻ...,010100002081080000D7E4180FDF2E59419FB4C379AEE2...,2026-07-04 19:49:06.727333,1257
2703,2704,5,322188 UA.I PW,119/21,2019-05-27,PRZEBUD.ROZBUD.BUDYNKÓW NADBUD.BUDYNKU OFICYNY...,010100002081080000995E4E2BFE2D5941693604F6A0E3...,2026-07-04 19:49:06.727333,1173

In [18]:

gdf_penalt = gpd.read_postgis(
    'SELECT * FROM mined.penalties',
    engine,
    geom_col='geometry'
)

gdf_penalt

,pen_id,date,place_of_penalty,pen_type,geometry
0,2535916,2019-01-14,ZIELONA 69,alcohol_consumption,POINT (6599216.29 5738180.99)
1,2396995,2019-01-19,PIOTRKOWSKA 70,alcohol_consumption,POINT (6600539.83 5738198.33)
2,5576927,2019-01-24,ZIELONA 33,alcohol_consumption,POINT (6599845.13 5738285.55)
3,9043443,2019-01-28,ZACHODNIA 55A,alcohol_consumption,POINT (6600109.96 5739144.39)
4,5596270,2019-01-28,ZACHODNIA 55A,alcohol_consumption,POINT (6600109.96 5739144.39)
...,...,...,...,...,...
1381,7502487,2023-02-18,Plac Wolności,offense,POINT (6600391.744 5739054.215)
1382,4495906,2023-02-18,Plac Wolności,offense,POINT (6600336.336 5739088.277)
1383,2938605,2023-02-18,Plac Wolności,offense,POINT (6600428.676 5739096.848)
1384,3618453,2020-08-06,Skwer Powstania Węgierskiego 1956 r.,offense,POINT (6600742.671 5737823.672)
1385,6175318,2020-08-06,Skwer Powstania Węgierskiego 1956 r.,offense,POINT (6600703.323 5737823.87)

In [22]:

gdf_app_prices = gpd.read_postgis(
    'SELECT * FROM mined.app_prices',
    engine,
    geom_col='geometry'
)

In [24]:
gdf_app_prices

,gml_id,res_unit_id,building_id,date,floor_no,floor_area,price_gross,block_id,geometry
0,ID_1_obj_id_226002223,106104_9.0018.119_BUD.152_LOK,106104_9.0018.119_BUD,2025-01-01,16.0,114.48,1381578.00,1276,POINT (6599107.424 5736817.861)
1,ID_1_obj_id_226975979,106105_9.0008.432_BUD.225_LOK,106105_9.0008.432_BUD,2025-01-01,3.0,49.54,531824.78,1251,POINT (6600716.008 5736553.426)
2,ID_1_obj_id_227690539,106105_9.0008.432_BUD.211_LOK,106105_9.0008.432_BUD,2025-01-01,1.0,48.24,473020.21,1251,POINT (6600716.008 5736553.426)
3,ID_1_obj_id_227804130,106105_9.0006.1245_BUD.20_LOK,106105_9.0006.1245_BUD,2025-01-01,2.0,38.34,300000.00,1180,POINT (6601345.092 5737924.464)
4,ID_1_obj_id_228086774,106103_9.0004.367_BUD.M110_LOK,106103_9.0004.367_BUD,2025-01-01,2.0,13.54,138000.00,1117,POINT (6601727.772 5735765.629)
...,...,...,...,...,...,...,...,...,...
26670,lokale.17762349,106103_9.0004.1237_BUD.16_LOK,106103_9.0004.1237_BUD,2026-03-19,3.0,48.54,496070.00,1019,POINT (6601535.457 5735695.741)
26671,lokale.17762157,106106_9.0024.1191_BUD.353_LOK,106106_9.0024.1191_BUD,2026-03-13,4.0,46.83,506489.29,1272,POINT (6602052.321 5738131.367)
26672,lokale.17762462,106103_9.0003.530_BUD.36_LOK,106103_9.0003.530_BUD,2026-02-23,4.0,28.37,170000.00,1124,POINT (6601438.073 5735431.577)
26673,lokale.17762466,106106_9.0024.1191_BUD.378_LOK,106106_9.0024.1191_BUD,2026-03-05,5.0,57.27,646647.14,1272,POINT (6602052.321 5738131.367)
26674,lokale.17761955,106104_9.0019.1066_BUD.39_LOK,106104_9.0019.1066_BUD,2026-02-06,7.0,37.79,411273.00,1240,POINT (6599556.279 5737715.677)

In [25]:

gdf_adr = gpd.read_postgis(
    'SELECT * FROM mined.adresses',
    engine,
    geom_col='geometry'
)

In [26]:
gdf_buildings = gpd.read_postgis(
    'SELECT * FROM mined.buildings',
    engine,
    geom_col='geometry'
)
gdf_buildings.crs

<Projected CRS: EPSG:2177>
Name: ETRF2000-PL / CS2000/18
Axis Info [cartesian]:
- x[north]: Northing (metre)
- y[east]: Easting (metre)
Area of Use:
- name: Poland - onshore and offshore between 16°30'E and 19°30'E.
- bounds: (16.5, 49.39, 19.5, 55.93)
Coordinate Operation:
- name: Poland CS2000 zone 6
- method: Transverse Mercator
Datum: ETRF2000 Poland
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [ ]:
gdf_buildings

In [ ]:
gdf_regen = gpd.read_postgis(
    'SELECT * FROM regeneration.actions',
    engine,
    geom_col='geometry'
)

In [ ]:
gdf = gpd.read_postgis(
    'SELECT * FROM core.urban_blocks_geom',
    engine,
    geom_col='geometry'
)
gdf.crs

In [ ]:
import folium
import webbrowser
import tempfile
def show_gdf_folium(gdf, fields=['kategoria_txt', 'nr_domu', 'year'], zoom_start=13):
    if gdf.empty:
        print("GeoDataFrame is empty.")
        return
    gdf_4326 = gdf.to_crs(epsg=4326)
    m = folium.Map(location=[0, 0], zoom_start=zoom_start)
    folium.GeoJson(
        gdf_4326,
        name="GeoDataFrame",
        tooltip=folium.GeoJsonTooltip(fields=fields,
                                      aliases=[f.replace("_", " ").title() for f in fields])
    ).add_to(m)
    folium.LayerControl().add_to(m)
    tmp_file = tempfile.NamedTemporaryFile(suffix='.html', delete=False)
    m.save(tmp_file.name)
    webbrowser.open(tmp_file.name)
    return m

In [ ]:
gdf_penalt2 = gdf_penalt[['pen_id', 'place_of_penalty', 'pen_type',	'geometry']].copy()

In [ ]:
show_gdf_folium(gdf_regen[['reg_id', 'type', 'costs','geometry']], fields=['reg_id', 'type', 'costs'], zoom_start=13)

In [ ]:
show_gdf_folium(gdf_penalt2, fields=['pen_id'], zoom_start=13)

In [ ]:
show_gdf_folium(gdf, fields=['block_id'], zoom_start=13)

In [ ]:
show_gdf_folium(gdf_penalt2, fields=['pen_id', 'place_of_penalty', 'pen_type'], zoom_start=13)

In [ ]:
gdf[['id','run_id','build_perm_id','build_plot_no']]

In [ ]:
df['year'].unique()

In [ ]:
# Dane geometryczne
gdf = gpd.read_postgis(
    "SELECT * FROM core.urban_blocks_geom LIMIT 5;",
    engine,
    geom_col="geometry"
)
gdf.plot()
gdf.head()