In [1]:
from sqlalchemy import create_engine, text
import pandas as pd
import geopandas as gpd

import folium
import webbrowser
import os
from folium.plugins import MarkerCluster

In [2]:



DATABASE_URL = "postgresql+psycopg2://urban_user:urban_password@localhost:5433/urban_db"
engine = create_engine(DATABASE_URL, pool_pre_ping=True)

with engine.connect() as conn:
    result = conn.execute(text("SELECT version();"))
    print(result.fetchone()[0])

PostgreSQL 16.4 (Debian 16.4-1.pgdg110+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

In [ ]:
# with engine.connect() as conn:
#     # Co jest w full_adress w stagingu?
#     print("=== stg_addresses (pierwsze 5) ===")
#     rows = conn.execute(text(
#         "SELECT full_adress FROM audit.stg_addresses WHERE run_id=11 LIMIT 5"
#     )).fetchall()
#     for r in rows: print(repr(r[0]))

#     print("\n=== stg_penalties - place_of_penalty (pierwsze 5) ===")
#     rows = conn.execute(text(
#         "SELECT place_of_penalty FROM audit.stg_penalties WHERE run_id=11 LIMIT 5"
#     )).fetchall()
#     for r in rows: print(repr(r[0]))

In [ ]:
# with engine.begin() as conn:
#     conn.execute(text("DELETE FROM mined.penalties"))
#     conn.execute(text("DELETE FROM audit.stg_penalties WHERE run_id=11"))
#     conn.execute(text("DELETE FROM audit.processed_files WHERE dag_id='etl_penalties_addresses'"))
#     print("OK")

In [ ]:
# with engine.begin() as conn:
#     conn.execute(text("DELETE FROM audit.stg_penalties WHERE run_id IN (SELECT run_id FROM audit.etl_log WHERE dag_id='etl_penalties_addresses')"))
#     conn.execute(text("DELETE FROM mined.penalties"))
#     conn.execute(text("DELETE FROM audit.processed_files WHERE dag_id='etl_penalties_addresses'"))
#     print("OK")

In [3]:
# Sprawdź dostępne schematy
with engine.connect() as conn:
    schemas = conn.execute(text(
        "SELECT schema_name FROM information_schema.schemata ORDER BY schema_name;"
    ))
    print([r[0] for r in schemas])

['audit', 'core', 'information_schema', 'legacy', 'meta', 'mined', 'osm', 'pg_catalog', 'pg_temp_10', 'pg_temp_17', 'pg_temp_19', 'pg_temp_20', 'pg_temp_21', 'pg_temp_22', 'pg_toast', 'pg_toast_temp_10', 'pg_toast_temp_17', 'pg_toast_temp_19', 'pg_toast_temp_20', 'pg_toast_temp_21', 'pg_toast_temp_22', 'public', 'regeneration', 'results']

In [4]:
# Sprawdź PostGIS
with engine.connect() as conn:
    result = conn.execute(text("SELECT PostGIS_Version();"))
    print("PostGIS:", result.fetchone()[0])

PostGIS: 3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

In [5]:
# Dane tabelaryczne
df = pd.read_sql("SELECT * FROM legacy.variables ", engine)
df

       block_id       year                   var_id      value
0          1004 2025-01-01  urVibEnAl_coun_00000000  31.000000
1          1005 2025-01-01  urVibEnAl_coun_00000000  79.000000
2          1006 2025-01-01  urVibEnAl_coun_00000000  19.000000
3          1007 2025-01-01  urVibEnAl_coun_00000000  56.000000
4          1008 2025-01-01  urVibEnAl_coun_00000000  16.000000
...         ...        ...                      ...        ...
12347      1280 2025-01-01  bdEnvFtxx_arrt_00000000   0.251552
12348      1281 2025-01-01  bdEnvFtxx_arrt_00000000   0.164316
12349      1282 2025-01-01  bdEnvFtxx_arrt_00000000   0.260939
12350      1283 2025-01-01  bdEnvFtxx_arrt_00000000   0.446308
12351      1284 2025-01-01  bdEnvFtxx_arrt_00000000   0.242072

[12352 rows x 4 columns]

In [6]:
# Dane tabelaryczne
df = pd.read_sql("SELECT * FROM mined.variables ", engine)
df

                       var_id       year  block_id  value
0     urVibBlPr_coun_00000000 2016-01-01      1001    0.0
1     urVibBlPr_coun_00000000 2017-01-01      1001    0.0
2     urVibBlPr_coun_00000000 2018-01-01      1001    0.0
3     urVibBlPr_coun_00000000 2019-01-01      1001    2.0
4     urVibBlPr_coun_00000000 2020-01-01      1001    0.0
...                       ...        ...       ...    ...
5655  urVibOfPn_coun_00000000 2019-01-01      1284    0.0
5656  urVibOfPn_coun_00000000 2020-01-01      1284    0.0
5657  urVibOfPn_coun_00000000 2021-01-01      1284    0.0
5658  urVibOfPn_coun_00000000 2022-01-01      1284    0.0
5659  urVibOfPn_coun_00000000 2023-01-01      1284    0.0

[5660 rows x 4 columns]

In [7]:
temp_check_df = df[(df['var_id'].isin(['urVibAlPn_coun_00000000', 'urVibOfPn_coun_00000000']))&(df['value'] != 0)]
temp_check_df

                       var_id       year  block_id  value
2863  urVibAlPn_coun_00000000 2022-01-01      1007    1.0
2875  urVibAlPn_coun_00000000 2019-01-01      1010    1.0
2878  urVibAlPn_coun_00000000 2022-01-01      1010    1.0
2891  urVibAlPn_coun_00000000 2020-01-01      1013    2.0
2894  urVibAlPn_coun_00000000 2023-01-01      1013    1.0
...                       ...        ...       ...    ...
5618  urVibOfPn_coun_00000000 2022-01-01      1276    1.0
5650  urVibOfPn_coun_00000000 2019-01-01      1283    2.0
5651  urVibOfPn_coun_00000000 2020-01-01      1283    2.0
5652  urVibOfPn_coun_00000000 2021-01-01      1283    2.0
5653  urVibOfPn_coun_00000000 2022-01-01      1283    1.0

[275 rows x 4 columns]

In [8]:
len(temp_check_df)

275

In [9]:
df[(df['year'] == pd.Timestamp('2025-01-01'))&(df['value'] != 0)]

                       var_id       year  block_id  value
109   urVibBlPr_coun_00000000 2025-01-01      1011    1.0
129   urVibBlPr_coun_00000000 2025-01-01      1013    2.0
139   urVibBlPr_coun_00000000 2025-01-01      1014    1.0
149   urVibBlPr_coun_00000000 2025-01-01      1015    2.0
179   urVibBlPr_coun_00000000 2025-01-01      1018    2.0
...                       ...        ...       ...    ...
2699  urVibBlPr_coun_00000000 2025-01-01      1271    2.0
2709  urVibBlPr_coun_00000000 2025-01-01      1272    5.0
2729  urVibBlPr_coun_00000000 2025-01-01      1274    1.0
2769  urVibBlPr_coun_00000000 2025-01-01      1278    3.0
2819  urVibBlPr_coun_00000000 2025-01-01      1283    7.0

[86 rows x 4 columns]

In [10]:
df = pd.read_sql("SELECT * FROM audit.etl_log ", engine)
df

,run_id,dag_id,source,started_at,finished_at,rows_extracted,rows_staged,rows_new,rows_loaded,status,error_msg
0,1,etl_build_perm,Geoportal GUNB WFS,2026-06-27 16:15:02.927989,NaT,NaN,NaN,NaN,NaN,running,None
1,2,etl_build_perm,Geoportal GUNB WFS,2026-06-27 16:20:59.605358,NaT,NaN,NaN,NaN,NaN,running,None
2,3,etl_build_perm,Geoportal GUNB WFS,2026-06-27 18:28:34.155154,NaT,NaN,NaN,NaN,NaN,running,None
3,4,etl_build_perm,Geoportal GUNB WFS,2026-06-27 18:36:21.411807,2026-06-27 18:36:47.436269,16845.0,1350.0,1350.0,1350.0,success,None
4,5,etl_build_perm,Geoportal GUNB WFS,2026-06-27 18:49:39.582830,2026-06-27 18:50:07.241741,16845.0,1350.0,0.0,0.0,success,None
5,6,etl_build_perm,Geoportal GUNB WFS,2026-06-27 19:17:50.135408,2026-06-27 19:18:17.759311,16845.0,1350.0,0.0,0.0,success,None
6,7,etl_build_perm,Geoportal GUNB WFS,2026-06-28 10:28:39.554827,2026-06-28 10:29:05.472144,16845.0,1350.0,0.0,0.0,success,None
7,8,etl_penalties_addresses,Geoportal GUNB WFS,2026-06-28 15:57:39.016280,NaT,NaN,NaN,NaN,NaN,running,None
8,9,etl_penalties_addresses,Geoportal GUNB WFS,2026-06-28 16:06:24.824647,2026-06-28 16:10:10.022791,12762.0,12762.0,91.0,12762.0,success,None
9,10,etl_penalties_addresses,Geoportal GUNB WFS,2026-06-28 16:21:36.021118,2026-06-28 16:21:55.195050,13032.0,13032.0,361.0,13032.0,success,None
10,11,etl_penalties_addresses,Geoportal GUNB WFS,2026-06-28 16:35:24.000970,2026-06-28 16:35:42.158529,13032.0,13032.0,361.0,13032.0,success,None
11,12,etl_penalties_addresses,Geoportal GUNB WFS,2026-06-28 16:47:29.236748,2026-06-28 16:47:46.814295,13032.0,13032.0,361.0,13032.0,success,None
12,13,etl_penalties_addresses,mapa_lodz/city_guard,2026-06-28 17:20:46.879458,2026-06-28 17:21:09.421480,14057.0,14057.0,1386.0,14057.0,success,None
13,14,etl_penalties_addresses,mapa_lodz/city_guard,2026-06-28 17:30:45.949071,2026-06-28 17:31:13.139272,14057.0,14057.0,1386.0,14057.0,success,None
14,15,etl_penalties_addresses,mapa_lodz/city_guard,2026-06-28 17:43:49.610239,2026-06-28 17:45:54.257799,14057.0,14057.0,1386.0,14057.0,success,None
15,16,etl_penalties_addresses,mapa_lodz/city_guard,2026-06-28 17:45:47.893875,2026-06-28 17:46:07.317693,12671.0,12671.0,0.0,12671.0,success,None

In [11]:
df = pd.read_sql("SELECT * FROM audit.stg_build_perm ", engine)
df

,id,run_id,build_perm_id,build_plot_no,issue_date,description,geometry,loaded_at,block_id
0,2701,6,833406 UA.I MB,155/3,2020-11-20,NADBUD.O JEDNĄ KONDYGNACJĘ BUDYNKU WIELOR.,0101000020810800006C74A9350D2F59410BDE99757BE4...,2026-06-27 19:18:09.010675,1279
1,2702,6,921676 UA.I,169/21,2020-12-30,"PRZEBUD.,NADBUD.I ZMIANA SPOS. UŻYTK.WRAZ Z PR...",010100002081080000D90B3DDFF42D5941FCFF6B45C0E4...,2026-06-27 19:18:09.010675,1224
2,2703,6,389382 UA.I PW,158/54,2020-06-10,BUDOWA BUDYNKU BIUROWEGO OZN. J01 ORAZ ROZBIÓR...,01010000208108000010786483812E5941CE3B2F6C78E1...,2026-06-27 19:18:09.010675,1132
3,2704,6,903478 UA.I,114/3,2020-12-21,"BUDOWA BUDYNKU WIELORODZINNEGO, ROZBIÓRKA BUDY...",01010000208108000091EE270A082E59416B90F99CB0E3...,2026-06-27 19:18:09.010675,1173
4,2705,6,728464 UA.III,62,2020-10-13,BUDOWA ZESP. SYSTEMOWYCH GARAŻY JEDNOSTAN.,01010000208108000017110635D72F59414B5F18DAA1E1...,2026-06-27 19:18:09.010675,1051
...,...,...,...,...,...,...,...,...,...
2695,5396,7,658616 UA.I,1/50,2019-10-30,"PRZEBUDOWA, NADBUDOWA, ZMIANA SPOSOBU UŻYTKOWA...",0101000020810800009E3BD4AFEB305941955E9151FEE2...,2026-06-28 10:28:59.248404,1027
2696,5397,7,39113 UA.I,270,2019-01-18,"BUDOWA,PRZEBUD.,NADBUD.,I ROZBUD. BUDYNKU KONF...",010100002081080000D865F6CD7C2D5941C04ED29E82E3...,2026-06-28 10:28:59.248404,1214
2697,5398,7,99096 UA.II,68/3,2019-02-13,BUDOWA BUDYNKU WIELORODZ.Z USŁUGAMI W PARTERZE...,010100002081080000BA4A8570B22C59417EAD0E1D7AE3...,2026-06-28 10:28:59.248404,1239
2698,5399,7,254216 UA.II,91/1,2019-04-18,PRZEBUD.ROZBUD.NADBUD.BUDYNKU BIUR-USŁUG. Z US...,010100002081080000325BFA04C82C5941E2EAB61A54E3...,2026-06-28 10:28:59.248404,1239
2699,5400,7,322188 UA.I PW,119/21,2019-05-27,PRZEBUD.ROZBUD.BUDYNKÓW NADBUD.BUDYNKU OFICYNY...,010100002081080000995E4E2BFE2D5941693604F6A0E3...,2026-06-28 10:28:59.248404,1173

In [12]:

gdf_penalt = gpd.read_postgis(
    'SELECT * FROM mined.penalties',
    engine,
    geom_col='geometry'
)
# gdf_penalt = gdf_penalt.set_crs(2177, allow_override=True)
# gdf_penalt_4326 = gdf_penalt.to_crs(4326)

In [15]:

gdf_adr = gpd.read_postgis(
    'SELECT * FROM mined.adresses',
    engine,
    geom_col='geometry'
)

In [18]:
gdf = gpd.read_postgis(
    'SELECT * FROM core.urban_blocks_geom',
    engine,
    geom_col='geometry'
)
gdf.crs

<Projected CRS: EPSG:2177>
Name: ETRF2000-PL / CS2000/18
Axis Info [cartesian]:
- x[north]: Northing (metre)
- y[east]: Easting (metre)
Area of Use:
- name: Poland - onshore and offshore between 16°30'E and 19°30'E.
- bounds: (16.5, 49.39, 19.5, 55.93)
Coordinate Operation:
- name: Poland CS2000 zone 6
- method: Transverse Mercator
Datum: ETRF2000 Poland
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [20]:
gdf = gpd.read_postgis(
    'SELECT * FROM audit.stg_build_perm',
    engine,
    geom_col='geometry'
)
gdf.crs

<Projected CRS: EPSG:2177>
Name: ETRF2000-PL / CS2000/18
Axis Info [cartesian]:
- x[north]: Northing (metre)
- y[east]: Easting (metre)
Area of Use:
- name: Poland - onshore and offshore between 16°30'E and 19°30'E.
- bounds: (16.5, 49.39, 19.5, 55.93)
Coordinate Operation:
- name: Poland CS2000 zone 6
- method: Transverse Mercator
Datum: ETRF2000 Poland
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [ ]:
gdf = gpd.read_postgis(
    'SELECT * FROM mined.penalties',
    engine,
    geom_col='geometry'
)
# gdf jest już w EPSG:4326 — nie nadpisuj CRS

m = folium.Map(
    location=[gdf.geometry.y.mean(), gdf.geometry.x.mean()],
    zoom_start=13
)
cluster = MarkerCluster().add_to(m)

for _, row in gdf.iterrows():
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=3,
        popup=str(row.get('place_of_penalty', ''))
    ).add_to(cluster)

out_path = os.path.abspath('penalties_map.html')
m.save(out_path)
webbrowser.open(f'file:///{out_path}')

In [ ]:


gdf = gpd.read_postgis(
    'SELECT * FROM audit.stg_build_perm WHERE run_id = 6',
    engine,
    geom_col='geometry'
)
gdf = gdf.set_crs(2177, allow_override=True)
gdf_4326 = gdf.to_crs(4326)

m = folium.Map(
    location=[gdf_4326.geometry.y.mean(), gdf_4326.geometry.x.mean()],
    zoom_start=13
)
cluster = MarkerCluster().add_to(m)

for _, row in gdf_4326.iterrows():
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=3,
        popup=str(row.get('description', ''))
    ).add_to(cluster)

out_path = os.path.abspath('build_permits_map.html')
m.save(out_path)
webbrowser.open(f'file:///{out_path}')
print(f'Mapa zapisana: {out_path}')

In [21]:
import folium
import webbrowser
import tempfile
def show_gdf_folium(gdf, fields=['kategoria_txt', 'nr_domu', 'year'], zoom_start=13):
    if gdf.empty:
        print("GeoDataFrame is empty.")
        return
    gdf_4326 = gdf.to_crs(epsg=4326)
    m = folium.Map(location=[0, 0], zoom_start=zoom_start)
    folium.GeoJson(
        gdf_4326,
        name="GeoDataFrame",
        tooltip=folium.GeoJsonTooltip(fields=fields,
                                      aliases=[f.replace("_", " ").title() for f in fields])
    ).add_to(m)
    folium.LayerControl().add_to(m)
    tmp_file = tempfile.NamedTemporaryFile(suffix='.html', delete=False)
    m.save(tmp_file.name)
    webbrowser.open(tmp_file.name)
    return m

In [22]:
gdf_penalt2 = gdf_penalt[['pen_id', 'place_of_penalty', 'pen_type',	'geometry']].copy()

In [23]:
show_gdf_folium(gdf_penalt2, fields=['pen_id', 'place_of_penalty', 'pen_type'], zoom_start=13)

In [ ]:
gdf[['id','run_id','build_perm_id','build_plot_no']]

In [ ]:
df['year'].unique()

In [ ]:
# Dane geometryczne
gdf = gpd.read_postgis(
    "SELECT * FROM core.urban_blocks_geom LIMIT 5;",
    engine,
    geom_col="geometry"
)
gdf.plot()
gdf.head()